leftnav:
- identifier: 0ac5f1b2-2a64-4d73-3fd0-b9bb116dde44
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: 648a9239-9e96-b460-6c79-a2860c07286f
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: c203b43b-40bc-28a8-2180-80c6b9e51b8c
  name: Readings
  url: /pages/readings
  weight: 30
- identifier: a9c3ffb8-256f-0ded-f7cf-d73158886d56
  name: Lecture Notes
  url: /pages/lecture-notes
  weight: 40
- identifier: 8f1d837e-7f09-ec4d-1600-7534b29e7a08
  name: Assignments
  url: /pages/assignments
  weight: 50
